version: '3.8'
services:
  asr-service:
    build: .
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia